### ISSUE TITLE
Call to a member function get_billing_country() on null

### ISSUE THREAD

**Issue by oftara** [heidelpay/woocommerce-heidelpay#10]
With iDeal payment method activated, I get the following error when editing the menus. 

_Uncaught Error: Call to a member function get_billing_country() on null in /public/wp-content/plugins/woocommerce-heidelpay-master/includes/gateways/class-wc-heidelpay-gateway-idl.php:137
Type: PHP Fatal error_

**Comment by Ryouzanpaku** [comment]
Solved in Version 1.2.0
